/// <reference types="cypress" />

// const homePage = `https://www.cleanlites.com/order`
const homePage = `http://localhost:3000`

describe('Order Form Loads', () => {
  beforeEach(() => cy.visit(homePage))
  it('Shows the home page', () => {
    cy.get('div.order-form-title h2').should('have.text', 'Online Order Form')
  })
})

describe('Order Form Loads', () => {
  let formJson
  before(() => {
    cy.viewport('macbook-15')
    cy.visit(homePage)
    cy.fixture('filled-out-form.json').then(function (data) {
      formJson = data
    })
  })

  it('Order Form Fill', () => {
    cy.get('label#pickup').click()
    cy.get('div.location-selector label').then((labels) => labels[0].click())
    // cy.wait(2000);
  })
  it('Billing', () => {
    const billingFields = [
      'billingAddress',
      'billingCity',
      'billingZip',
      'billingEmail',
      'billingCompany',
      'billingContactName',
      'billingPhone',
    ]

    billingFields.forEach((f) => {
      cy.get(`#billingForm input[name='${f}']`).type(formJson[f])
      // inputs.map((i) => cy.get(`input[name='${i.name}']`)).type("test");
    })

    cy.get('#billingForm select').select(formJson['billingState'])
    cy.get('button#btn-next').click()
  })
  it('Generator', () => {
    cy.get('#generatorForm .big-button label').click()
  })
  it('Material Selector', () => {
    cy.get('.material-picker--wrapper .material-picker--selector').each(
      ($el) => {
        cy.wrap($el).click()
      }
    )
    cy.get('.progress-nodes .sub-item--ul li').should('have.length', 6)
    cy.get('button#btn-next').click()
  })

  it(`Can fill in: Ballast`, () => {
    cy.get(`.material-holder #ballast input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it(`Can fill in: Batteries`, () => {
    cy.get(`.material-holder #batteries input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it(`Can fill in: EWaste`, () => {
    cy.get(`.material-holder #ewaste input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it(`Can fill in: Haz`, () => {
    cy.get(`.material-holder #haz input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it(`Can fill in: Lamps`, () => {
    cy.get(`.material-holder #lamps input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it(`Can fill in: Specialty`, () => {
    cy.get(`.material-holder #specialty input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })

  it('Containers', () => {
    cy.get(`.containers input[type=text]`).each(($el) => {
      cy.wrap($el).type(200)
    })
    cy.get('button#btn-next').click()
  })
  it('Site Details', () => {
    cy.get(`input[name='heightRestrictions']`).type('None')
    cy.get(`input[name='noPallets']`).type(12345)
    cy.get(`input[name='estTotalWeight']`).type(4500)
    cy.get(`textarea[name='comments']`).type(
      `This order was auto generated by cypress testing.`
    )
    cy.get(`.site-info label`).each(($el) => {
      cy.wrap($el).click()
    })
  })
})

describe('Order Form Upload File', () => {
  it('Can upload file', () => {
    // cy.get("input[type=file]").selectFile("cypress/fixtures/logo.png");
    // cy.get('button#btn-submit').click()
  })
})

describe('Order Form Submits', () => {
  it('Can go to submit page', () => {
    // cy.get("input[type=file]").selectFile("cypress/fixtures/logo.png");
    cy.get('button#btn-submit').click()
  })
  it('Confirm Page', () => {
    cy.wait(1500)
    // cy.get('.rendered-section__submit button#submit-form').click()
    // console.log(cy.get('.rendered-section__submit'))
  })
})
