# https://t.hegu.it/deploy-on-ftp-with-github-actions/
name: Production Deploy
on:
  push:
    branches:
      - production
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  build-deploy:
    needs: cancel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # build using the page build on data change
      - name: fake-dir
        run: mkdir test-dir && cd test-dir && touch test.txt && cd ../
      # - name: install
      #   run: npm ci
      # - name: build
      #   run: npm run build --if-present
      #   env:
      #     CI: false
      # - name: Upload public dir
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: order
      #     # https://dev.to/danielbayerlein/incremental-gatsby-builds-with-github-actions-2p7o
      #     path: build/
      - name: List output files
        run: ls
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 25734
          source: 'test-dir'
          target: ~/public/order
